<a href="https://colab.research.google.com/github/abdulhadi9575/Abstraction-and-Polymorphism/blob/main/Welcome_to_data_scince.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

data_type=[('name', 'S15'),('class',int),('height', float)]
students_details = [('james',5,48.5), ('nail',6,52.5),('paul',5,42.10),('pit',5,40.11)]

students=np.array(students_details,dtype=data_type)
print("Orignal array:")
print(students)
print("Sort by height")
print(np.sort(students,order='height'))


Orignal array:
[(b'james', 5, 48.5 ) (b'nail', 6, 52.5 ) (b'paul', 5, 42.1 )
 (b'pit', 5, 40.11)]
Sort by height
[(b'pit', 5, 40.11) (b'paul', 5, 42.1 ) (b'james', 5, 48.5 )
 (b'nail', 6, 52.5 )]


In [2]:
import numpy as np

arr=np.array([1,2,3,4,5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
import numpy as np

arr=np.array([1,2,3,4])

print(arr[0])

1


In [4]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7])

print(arr[1:5])

[2 3 4 5]


In [5]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr.dtype)

int64


In [6]:
import numpy as np
arr=np.array([1,2,3])
for x in arr:
  print(x)

1
2
3


In [7]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [9]:
import numpy as np
arr=np.array([1,2,3,4],dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1
