<a href="https://colab.research.google.com/github/abdulhadi9575/Abstraction-and-Polymorphism/blob/main/Welcome_to_data_scince.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

data_type=[('name', 'S15'),('class',int),('height', float)]
students_details = [('james',5,48.5), ('nail',6,52.5),('paul',5,42.10),('pit',5,40.11)]

students=np.array(students_details,dtype=data_type)
print("Orignal array:")
print(students)
print("Sort by height")
print(np.sort(students,order='height'))


Orignal array:
[(b'james', 5, 48.5 ) (b'nail', 6, 52.5 ) (b'paul', 5, 42.1 )
 (b'pit', 5, 40.11)]
Sort by height
[(b'pit', 5, 40.11) (b'paul', 5, 42.1 ) (b'james', 5, 48.5 )
 (b'nail', 6, 52.5 )]


In [2]:
import numpy as np

arr=np.array([1,2,3,4,5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
import numpy as np

arr=np.array([1,2,3,4])

print(arr[0])

1


In [4]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7])

print(arr[1:5])

[2 3 4 5]


In [5]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr.dtype)

int64


In [6]:
import numpy as np
arr=np.array([1,2,3])
for x in arr:
  print(x)

1
2
3


In [7]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [9]:
import numpy as np
arr=np.array([1,2,3,4],dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [1]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [2]:
import numpy as np
arr=np.array([1,2,3,4,5,4,4])
x=np.where(arr==4)
print(x)

(array([3, 5, 6]),)


In [11]:
from numpy import random
x=random.randint(100)
print(x)

38


In [14]:
import numpy as np

a=np.arange(9,dtype=float).reshape(3,3)
print('first array:')
print(a)
print('\n')

b=np.array([10,10,10])
print('second array:')
print(b)
print('\n')

print('add the two arrays:')
print(np.add(a,b))
print('\n')

print('subtract the two arrays:')
print(np.subtract(a,b))
print('\n')

print('multiply the two arrays:')
print(np.multiply(a,b))
print('\n')

print('divide the two arrays:')
print(np.divide(a,b))
print('\n')

first array:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


second array:
[10 10 10]


add the two arrays:
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]


subtract the two arrays:
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]


multiply the two arrays:
[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]


divide the two arrays:
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


